//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NpcEditor {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NpcEditor.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reset.
        /// </summary>
        internal static string buttonHitboxReset_Text {
            get {
                return ResourceManager.GetString("buttonHitboxReset.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save.
        /// </summary>
        internal static string buttonHitboxSave_Text {
            get {
                return ResourceManager.GetString("buttonHitboxSave.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to load swf animation.
        /// </summary>
        internal static string buttonLoadAnim_Text {
            get {
                return ResourceManager.GetString("buttonLoadAnim.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load map.
        /// </summary>
        internal static string buttonLoadMap_Text {
            get {
                return ResourceManager.GetString("buttonLoadMap.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reload tool swf.
        /// </summary>
        internal static string buttonReloadSwf_Text {
            get {
                return ResourceManager.GetString("buttonReloadSwf.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi select (Only same ModelID).
        /// </summary>
        internal static string checkBoxMulti_Text {
            get {
                return ResourceManager.GetString("checkBoxMulti.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlashCall işlenirken bir hata oluştu. .
        /// </summary>
        internal static string FlashCallError {
            get {
                return ResourceManager.GetString("FlashCallError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search NPC.
        /// </summary>
        internal static string groupBoxSearchNpc_Text {
            get {
                return ResourceManager.GetString("groupBoxSearchNpc.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected NPC.
        /// </summary>
        internal static string groupBoxSelectedNpc_Text {
            get {
                return ResourceManager.GetString("groupBoxSelectedNpc.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map:.
        /// </summary>
        internal static string label7_Text {
            get {
                return ResourceManager.GetString("label7.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developed by:.
        /// </summary>
        internal static string labelDevBy_Text {
            get {
                return ResourceManager.GetString("labelDevBy.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        internal static string labelLanguage_Text {
            get {
                return ResourceManager.GetString("labelLanguage.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The program will not run correctly because the {0} file cannot be found..
        /// </summary>
        internal static string LoaderSwfNotFound {
            get {
                return ResourceManager.GetString("LoaderSwfNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The map you selected was not found..
        /// </summary>
        internal static string MapNotFound {
            get {
                return ResourceManager.GetString("MapNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You did not choose a map..
        /// </summary>
        internal static string MapNotSelected {
            get {
                return ResourceManager.GetString("MapNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hitbox data is invalid. Data must be numbers only!.
        /// </summary>
        internal static string NpcHitboxInvalidData {
            get {
                return ResourceManager.GetString("NpcHitboxInvalidData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NPC hitbox updated..
        /// </summary>
        internal static string NpcHitboxUpdated {
            get {
                return ResourceManager.GetString("NpcHitboxUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save NPC hitbox. Please try again..
        /// </summary>
        internal static string NpcHitboxUpdateError {
            get {
                return ResourceManager.GetString("NpcHitboxUpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NPC is not selected..
        /// </summary>
        internal static string NpcNotSelected {
            get {
                return ResourceManager.GetString("NpcNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not selected.
        /// </summary>
        internal static string textBoxSelectedNpcID_Text {
            get {
                return ResourceManager.GetString("textBoxSelectedNpcID.Text", resourceCulture);
            }
        }
    }
}
